server:
  port: 9092
spring:
  application:
    name: basket
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_basket_db
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/